version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=HsupermarioM@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/softoom-frontend-xiaoconan
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=j.softoom.space
      - LETSENCRYPT_HOST=j.softoom.space
  backend:
    image: ghcr.io/uoft-utsc-cs-sandbox/softoom-backend-xiaoconan
    container_name: backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.j.softoom.space
      - LETSENCRYPT_HOST=api.j.softoom.space
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H1092387456M
      POSTGRES_DB: appData
    ports:
      - 5433:5433
    volumes:
      - ./pgdata:/var/lib/postgresql/data
